name: Internal technical issue
description: Change the code base without affecting users
title: 'Internal: '
labels: 'internal'
body:
- type: input
  id: reference
  attributes:
    label: Reference
    description:
