# This is a basic workflow to help you get started with Actions
name: Test

on:
  push:
  pull_request:

jobs:
  Tests:
    runs-on: macOS-latest
    steps:
      - name: "Select Xcode 13.0.0"
        uses: devbotsxyz/xcode-select@v1
        with:
          version: "13"
      - uses: actions/checkout@v1
      - name: Install xcbeautify
        run: brew install xcbeautify
      - name: Run unit tests
        run: xcodebuild -scheme MeetingBar test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcbeautify
